
#include<stdio.h>

int main() {
    char memory[10000];
    int index = 0;

    for (int i=0; i < 10000; i++) {
        memory[i] = 0;
    }

    memory[index] = getchar(); fflush(stdin);
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    index += 1;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    printf("%c", memory[index]);
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index] = getchar(); fflush(stdin);
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    index += 1;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    printf("%c", memory[index]);
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    memory[index]--;
    index -= 1;
    index -= 1;
    while(memory[index] != 0) {
    memory[index]--;
    index += 1;
    memory[index]++;
    index -= 1;
    }
    index += 1;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    printf("%c", memory[index]);
    index += 1;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    memory[index]++;
    printf("%c", memory[index]);
   return 0;
}
